spring:
  config:
    import:
      - application-security.yml
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_CONSOLE_URL}
    username: ${H2_CONSOLE_ID}
    password: ${H2_CONSOLE_PW}
  jpa:
    hibernate:
      ddl-auto: create # todo: 추후 none 으로 변경할 것
    properties:
      hibernate:
        format_sql: true