jwt:
  secret: ${JWT_SECRET}
  atk_expiration: ${JWT_ATK_EXPIRATION}
  rtk_expiration: ${JWT_RTK_EXPIRATION}
  reissue_url: ${JWT_REISSUE_URL}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
